collections:
  - blocks
  - basic
  - ramps

views:
  north_west:
    deg0:
      base_0:
        flip_h: false
      base_0_face:
        flip_h: true
        color: 0x30FFFFFF
    deg90:
      base_90:
        flip_h: true
      base_90_face:
        flip_h: true
        color: 0x30FFFFFF
    deg180:
      base_180:
        flip_h: false
      base_180_side:
        flip_h: true
        color: 0x30FFFFFF
    deg270:
      base_90:
        flip_h: false
      base_90_side:
         flip_h: false
         color: 0x30FFFFFF
  north_east:
    deg0:
      base_90:
        flip_h: false
      base_90_face:
        flip_h: false
        color: 0x30FFFFFF
    deg90:
      base_0:
        flip_h: false
    deg180:
      base_90:
        flip_h: true
    deg270:
      base_180:
        flip_h: false
  south_west:
    deg0:
      base_90:
        flip_h: true
    deg90:
      base_180:
        flip_h: false
    deg180:
      base_90:
        flip_h: false
    deg270:
      base_0:
        flip_h: false
  south_east:
    deg0:
      base_180:
        flip_h: false
    deg90:
      base_90:
        flip_h: false
    deg180:
      base_0:
        flip_h: false
    deg270:
      base_90:
        flip_h: true