collections:
  - blocks
  - basic

views:
  north_west:
    deg0:
      base_180:
        flip_h: true
      base_180_side_light:
        flip_h: true
        color: 0x10ffffff
    deg90:
      base:
        filp_h: true
      base_light_ramp:
        flip_h: true
        color: 0x10ffffff
    deg180:
      base:
        flip_h: false
      base_side_light:
        flip_h: false
        color: 0x10ffffff
    def270:
      base_180:
        flip_h: false
      base_180_back_light:
        flip_h: false
        color: 0x10ffffff
  north_east:
    deg0:
    deg90:
    deg180:
    def270:
  south_west:
    deg0:
    deg90:
    deg180:
    def270:
  south_east:
    deg0:
    deg90:
    deg180:
    def270: