
# Name what collections this block belongs to
collections:
  - example
  - example_collection

# List of four views (NW SW NE SE) which hold rotations which hold the layers which hold the assets to draw.
views:
  # {north_west: north_east: south_east: south_west:}
  direction:
    # if it has no rotation (:all means draw on all layers and overrides other rotations)
    # [:deg0, :deg90, :deg180, :deg270]
    rotation:
      block_asset_name: none